version: '3'
services:
  nginx:
    restart: unless-stopped
    container_name: lucadibello-webserver
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/letsencrypt/well-known:/data/well-known
  certbot: 
    image: certbot/certbot
    restart: unless-stopped
    command: "certonly --verbose --webroot --non-interactive --agree-tos --renew-by-default \
    --preferred-challenges http-01 --server https://acme-v02.api.letsencrypt.org/directory \
    --text --email info@lucadibello.ch \
    -w /etc/letsencrypt/well-known -d lucadibello.ddns.net"
    container_name: lucadibello-certbot
    environment:
      CERTBOT_EMAIL: info@lucadibello.ch
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/letsencrypt/well-known:/etc/letsencrypt/well-known
      - /var/lib/letsencrypt:/var/lib/letsencrypt
volumes:
  nginx_secrets: