# Docker compose file for running the application
networks:
  default:
    external:
      name: lucadibello-website-network

version: '3'
services:
  website:
    container_name: lucadibello-website
    # Build the image from the Dockerfile in the current directory
    # and tag it with the name `website`
    build: .
    # Expose port 80 of the container to port 80 of the host
    ports:
      - "80:3000"