# Docker compose file for running the application
networks:
  default:
    external:
      name: lucadibello-website-network

version: '3'
services:
  website:
    container_name: lucadibello-website
    image: lucadibello/website:latest
    ports:
      - "80:3000"